export const fakeItems = [
  {
    id: 1,
    user_id: -1,
    name: "Квартира в центре",
    description: "Просторная квартира в центре города",
    location: "Москва",
    type: "Недвижимость",
    propertyType: "Квартира",
    area: 100,
    rooms: 3,
    price: 15000000,
  },
  {
    id: 2,
    user_id: -1,
    name: "Загородный дом",
    description: "Уютный дом с большим садом",
    location: "Московская область",
    type: "Недвижимость",
    propertyType: "Дом",
    area: 200,
    rooms: 5,
    price: 25000000,
  },
  {
    id: 3,
    user_id: -1,
    name: "Toyota Camry",
    description: "Надежный автомобиль",
    location: "Москва",
    type: "Авто",
    brand: "Toyota",
    model: "Camry",
    year: 2020,
    mileage: 15000,
  },
  {
    id: 4,
    user_id: -1,
    name: "BMW X5",
    description: "Полностью обслуженный автомобиль",
    location: "Санкт-Петербург",
    type: "Авто",
    brand: "BMW",
    model: "X5",
    year: 2018,
    mileage: 45000,
  },
  {
    id: 5,
    user_id: -1,
    name: "Ремонт квартир",
    description: "Качественный ремонт квартир",
    location: "Москва",
    type: "Услуги",
    serviceType: "Ремонт",
    experience: 5,
    cost: 50000,
    workSchedule: "Пн-Пт, 9:00-18:00",
  },
  {
    id: 6,
    user_id: -1,
    name: "Репетитор по математике",
    description: "Подготовка к экзаменам, ЕГЭ и ОГЭ",
    location: "Москва",
    type: "Услуги",
    serviceType: "Обучение",
    experience: 10,
    cost: 2000,
    workSchedule: "Пн-Сб, 10:00-20:00",
  },
  {
    id: 7,
    user_id: -1,
    name: "Ford Focus",
    description: "Экономичный автомобиль",
    location: "Казань",
    type: "Авто",
    brand: "Ford",
    model: "Focus",
    year: 2017,
    mileage: 80000,
  },
  {
    id: 8,
    user_id: -1,
    name: "Дизайн интерьеров",
    description: "Создание стильных интерьеров",
    location: "Екатеринбург",
    type: "Услуги",
    serviceType: "Дизайн",
    experience: 7,
    cost: 70000,
    workSchedule: "Пн-Сб, 10:00-19:00",
  },
  {
    id: 9,
    user_id: -1,
    name: "iPhone 13 Pro",
    description: "Новый телефон в упаковке",
    location: "Москва",
    type: "Техника",
    brand: "Apple",
    model: "iPhone 13 Pro",
    price: 95000,
  },
  {
    id: 10,
    user_id: -1,
    name: "Садовый участок",
    description: "Земля для строительства дома",
    location: "Краснодарский край",
    type: "Недвижимость",
    propertyType: "Участок",
    area: 500,
    price: 3000000,
  },
  {
    id: 1,
    user_id: -1,
    name: "Офис в центре",
    description: "Просторный офис с ремонтом",
    location: "Москва",
    type: "Недвижимость",
    propertyType: "Офис",
    area: 150,
    rooms: 4,
    price: 30000000,
  },
  {
    id: 2,
    user_id: -1,
    name: "Гараж в спальном районе",
    description: "Теплый гараж, удобный подъезд",
    location: "Санкт-Петербург",
    type: "Недвижимость",
    propertyType: "Гараж",
    area: 20,
    price: 500000,
  },
  {
    id: 3,
    user_id: -1,
    name: "Mercedes-Benz E-Class",
    description: "Комфортный и надежный автомобиль",
    location: "Казань",
    type: "Авто",
    brand: "Mercedes-Benz",
    model: "E-Class",
    year: 2021,
    mileage: 10000,
  },
  {
    id: 4,
    user_id: -1,
    name: "Hyundai Solaris",
    description: "Экономичный и удобный авто",
    location: "Екатеринбург",
    type: "Авто",
    brand: "Hyundai",
    model: "Solaris",
    year: 2019,
    mileage: 45000,
  },
  {
    id: 5,
    user_id: -1,
    name: "Сантехнические работы",
    description: "Установка и ремонт сантехники",
    location: "Москва",
    type: "Услуги",
    serviceType: "Сантехника",
    experience: 8,
    cost: 25000,
    workSchedule: "Пн-Сб, 9:00-19:00",
  },
  {
    id: 6,
    user_id: -1,
    name: "Ландшафтный дизайн",
    description: "Благоустройство садов и участков",
    location: "Сочи",
    type: "Услуги",
    serviceType: "Дизайн",
    experience: 10,
    cost: 100000,
    workSchedule: "Пн-Пт, 10:00-18:00",
  },
  {
    id: 7,
    user_id: -1,
    name: "Шиномонтаж и балансировка",
    description: "Быстрое и качественное обслуживание",
    location: "Краснодар",
    type: "Услуги",
    serviceType: "Автосервис",
    experience: 6,
    cost: 5000,
    workSchedule: "Пн-Сб, 8:00-20:00",
  },
  {
    id: 8,
    user_id: -1,
    name: "Samsung Galaxy S23",
    description: "Флагманский смартфон, новый",
    location: "Москва",
    type: "Техника",
    brand: "Samsung",
    model: "Galaxy S23",
    price: 85000,
  },
  {
    id: 9,
    user_id: -1,
    name: "Ноутбук ASUS ROG",
    description: "Мощный игровой ноутбук",
    location: "Санкт-Петербург",
    type: "Техника",
    brand: "ASUS",
    model: "ROG Strix G15",
    price: 120000,
  },
  {
    id: 10,
    user_id: -1,
    name: "Земельный участок под строительство",
    description: "Отличное место для загородного дома",
    location: "Тверская область",
    type: "Недвижимость",
    propertyType: "Участок",
    area: 1000,
    price: 2500000,
  },
  {
    id: 11,
    user_id: -1,
    name: "Volkswagen Tiguan",
    description: "Кроссовер в отличном состоянии",
    location: "Москва",
    type: "Авто",
    brand: "Volkswagen",
    model: "Tiguan",
    year: 2022,
    mileage: 5000,
  },
  {
    id: 12,
    user_id: -1,
    name: "Строительство бань и саун",
    description: "Под ключ, качественные материалы",
    location: "Новосибирск",
    type: "Услуги",
    serviceType: "Строительство",
    experience: 12,
    cost: 400000,
    workSchedule: "Пн-Сб, 9:00-18:00",
  },
];
